### ISSUE TITLE
The change_volume function got broken in commit e9ec867

### ISSUE THREAD

**Issue by JanKoudijs** [RoonLabs/node-roon-api-transport#4]
The change_volume function got broken in commit e9ec867.
Parameter 'z' changed to 'output' in the parameter list, but this rename is not performed at the next line, causing an exception:

    node-roon-api-transport/lib.js:146
        if (!z) { if (cb) cb(false); return; }
             ^
    
    ReferenceError: z is not defined
        at RoonApiTransport.change_volume (/home/Jan/devel/roon/extensions/roon-extension-alarm-clock/sources/node_modules/node-roon-api-transport/lib.js:146:10)
        at Timeout.take_fade_step [as _onTimeout] (/home/Jan/devel/roon/extensions/roon-extension-alarm-clock/sources/alarm-clock.js:536:44)
        at ontimeout (timers.js:375:18)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

**Comment by dannyfiresnake** [comment]
fixed in 92df1a8
